### ISSUE TITLE
Controllability Analysis and Optimal Control of Mixed Traffic Flow With Human-Driven and Autonomous Vehicles

### ISSUE THREAD

**Issue by YiXiangfeng521** [soc-ucsd/mixed-traffic#4]
作者您好！感谢您分享的精彩的工作！我最近在拜读您题为“Controllability Analysis and Optimal Control of Mixed Traffic Flow With Human-Driven and Autonomous Vehicles”的这篇文章，我有一个疑惑，想要向您请教一下，还请不吝赐教！
![image](https://github.com/soc-ucsd/mixed-traffic/assets/147248733/03d813c9-69c2-4a2e-86f3-6d462d2d0e08)
请问图中红框的部分是如何得到的？我按照论文里的方法得到的结果似乎和论文里不一样。

**Comment by YiXiangfeng521** [comment]
我又重新推导了一下，确实得到了您论文中的结果。但是，我不知道这么做是否是正确的，您能帮我看一下吗？
![2f8766506838c158a1220841b29bf71a](https://github.com/soc-ucsd/mixed-traffic/assets/147248733/53b85237-621e-4fde-88d0-ec0e959ebee3)

**Comment by wangjw18** [comment]
您好，感谢留言。推导过程基本差不多，有一个小问题，第一个公式的左边第二个矩阵应该是$`\begin{bmatrix}Q^{1/2}&-K^T R^{1/2}\end{bmatrix}`$吧。

**Comment by YiXiangfeng521** [comment]
> 您好，感谢留言。推导过程基本差不多，有一个小问题，第一个公式的左边第二个矩阵应该是[Q1/2−KTR1/2]吧。

感谢您在百忙之中回答我的提问。
![image](https://github.com/soc-ucsd/mixed-traffic/assets/147248733/f58ecdd8-42cd-46d8-b7b3-e58f740ff931)应该是一个1x1的标量实数吧，放在左边或者右边应该都不影响吧？

**Comment by wangjw18** [comment]
是的，对于本文中仅一辆CAV的情形是这样的。

**Comment by YiXiangfeng521** [comment]
> 是的，对于本文中仅一辆CAV的情形是这样的。

好的，再次感谢您的回复！
